# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class FlatFootprint(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, size: int=None, units: str=None):  # noqa: E501
        """FlatFootprint - a model defined in Swagger

        :param size: The size of this FlatFootprint.  # noqa: E501
        :type size: int
        :param units: The units of this FlatFootprint.  # noqa: E501
        :type units: str
        """
        self.swagger_types = {
            'size': int,
            'units': str
        }

        self.attribute_map = {
            'size': 'size',
            'units': 'units'
        }
        self._size = size
        self._units = units

    @classmethod
    def from_dict(cls, dikt) -> 'FlatFootprint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The flatFootprint of this FlatFootprint.  # noqa: E501
        :rtype: FlatFootprint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def size(self) -> int:
        """Gets the size of this FlatFootprint.


        :return: The size of this FlatFootprint.
        :rtype: int
        """
        return self._size

    @size.setter
    def size(self, size: int):
        """Sets the size of this FlatFootprint.


        :param size: The size of this FlatFootprint.
        :type size: int
        """

        self._size = size

    @property
    def units(self) -> str:
        """Gets the units of this FlatFootprint.


        :return: The units of this FlatFootprint.
        :rtype: str
        """
        return self._units

    @units.setter
    def units(self, units: str):
        """Sets the units of this FlatFootprint.


        :param units: The units of this FlatFootprint.
        :type units: str
        """

        self._units = units
