# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Purchase(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    def __init__(self, purchase_date: str=None, purchase_amount: int=None, purchase_currency: str=None):  # noqa: E501
        """Purchase - a model defined in Swagger

        :param purchase_date: The purchase_date of this Purchase.  # noqa: E501
        :type purchase_date: str
        :param purchase_amount: The purchase_amount of this Purchase.  # noqa: E501
        :type purchase_amount: int
        :param purchase_currency: The purchase_currency of this Purchase.  # noqa: E501
        :type purchase_currency: str
        """
        self.swagger_types = {
            'purchase_date': str,
            'purchase_amount': int,
            'purchase_currency': str
        }

        self.attribute_map = {
            'purchase_date': 'purchaseDate',
            'purchase_amount': 'purchaseAmount',
            'purchase_currency': 'purchaseCurrency'
        }
        self._purchase_date = purchase_date
        self._purchase_amount = purchase_amount
        self._purchase_currency = purchase_currency

    @classmethod
    def from_dict(cls, dikt) -> 'Purchase':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The purchase of this Purchase.  # noqa: E501
        :rtype: Purchase
        """
        return util.deserialize_model(dikt, cls)

    @property
    def purchase_date(self) -> str:
        """Gets the purchase_date of this Purchase.

        The date on which the house was purchased  # noqa: E501

        :return: The purchase_date of this Purchase.
        :rtype: str
        """
        return self._purchase_date

    @purchase_date.setter
    def purchase_date(self, purchase_date: str):
        """Sets the purchase_date of this Purchase.

        The date on which the house was purchased  # noqa: E501

        :param purchase_date: The purchase_date of this Purchase.
        :type purchase_date: str
        """

        self._purchase_date = purchase_date

    @property
    def purchase_amount(self) -> int:
        """Gets the purchase_amount of this Purchase.

        The amount, in whole units, that the property was purchased for  # noqa: E501

        :return: The purchase_amount of this Purchase.
        :rtype: int
        """
        return self._purchase_amount

    @purchase_amount.setter
    def purchase_amount(self, purchase_amount: int):
        """Sets the purchase_amount of this Purchase.

        The amount, in whole units, that the property was purchased for  # noqa: E501

        :param purchase_amount: The purchase_amount of this Purchase.
        :type purchase_amount: int
        """

        self._purchase_amount = purchase_amount

    @property
    def purchase_currency(self) -> str:
        """Gets the purchase_currency of this Purchase.

        The local currency that was used in the purchase of the property  # noqa: E501

        :return: The purchase_currency of this Purchase.
        :rtype: str
        """
        return self._purchase_currency

    @purchase_currency.setter
    def purchase_currency(self, purchase_currency: str):
        """Sets the purchase_currency of this Purchase.

        The local currency that was used in the purchase of the property  # noqa: E501

        :param purchase_currency: The purchase_currency of this Purchase.
        :type purchase_currency: str
        """

        self._purchase_currency = purchase_currency
